import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar"
import Footer from "@/components/footer/Footer"
import Divider from "@/components/divider/divider"

const karla = Karla({ 
  subsets: ["latin"],
  weight: ["200", "300", "400", "500"]
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true} className={`bg-yel low-50 ${karla.className}`}>
        <div className="navbar">
          <Navbar />
        </div>
        {children}
        <Divider />
        {/* <Footer /> */}
      </body>
    </html>
  );
}
