import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar"
import Footer from "@/components/footer/Footer"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true} className={`bg-gradient-to-t from-purple-200 via-blue-200 to-indigo-200 ${inter.className}`}>
        <div className="navbar">
          <Navbar />
        </div>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
